name: CI

on:
  pull_request:
    branches: ["develop", "main"]
    paths:
      - "fish-clicks-api/**"
      - ".github/workflows/**"
  push:
    branches: ["develop", "main"]
    paths:
      - "fish-clicks-api/**"
      - ".github/workflows/**"

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Build & test (no chmod needed)
        working-directory: fish-clicks-api
        shell: bash
        run: bash ./mvnw -B clean verify